services:
  db:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: foobarhogepiyo
    ports:
      - 33306:3306
    volumes:
      - data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8888:8080
volumes:
  data:
